### ISSUE TITLE
Map on the location tab

### ISSUE THREAD

**Issue by artemshulgin** [MedPoints/site#10]
This is a current situation of the map
![image](https://user-images.githubusercontent.com/35609528/43276278-d724ca20-910c-11e8-91d1-23af03714c93.png)

Location's api returns hospitals with coordinates
We need to show them up on them map
```javascript
{
    worldsCount : 123,
    locations : 
 [ 
    {
        name : "US",
        count : 12,
        hospitals : [
           { .... coordinations : { lat, lng} }
         ]
    }
 ]
}
```

**Comment by k0t0v** [comment]
Implemented maps across all locations pages
