### ISSUE TITLE
Clinic description

### ISSUE THREAD

**Issue by artemshulgin** [MedPoints/site#11]
Currently clinics are displayed like in the picture below

![image](https://user-images.githubusercontent.com/35609528/43314159-ca52676a-919a-11e8-8fd6-3ace9d0bce8a.png)

But they should be displayed with meta-data

![image](https://user-images.githubusercontent.com/35609528/43314488-bfd3a8ca-919b-11e8-8881-f9b4029d5de7.png)

**Comment by k0t0v** [comment]
Couple of questions arose when I started fixing this issue:

Specilalizations meta: For specializations we need a full array of related specializations for a hospital. A specialization object should contain at least a specialization name and a specialiation id. This is the minimum of data required to display links for specializations.


Location meta: It is not clear how should the links in the location meta be built. I'll display a string value for now.

Photo meta: the property is called 'photos', but ther's only one url in it. What will the future structure of the object be? Also, how will we store gallery images?

Description: what property will hold the description text? I also assume that it will be HTML text, not the plain text, am I correct?

Would be happy if @artemshulgin could answer all of them.

**Comment by artemshulgin** [comment]
@k0t0v Specialisations meta  - ok, api will be prepared for you
Location meta - please, create link to the map maps.google.com
Photo meta - it is only one photo, and this is our current format of the data
Description : Please, place "lorum ipsum" etc.

**Comment by k0t0v** [comment]
@artemshulgin implemented all tasks from this issue. Regarding the specializations meta - please create a new issue as soon as the API is ready.
