### ISSUE TITLE
remove useless elements

### ISSUE THREAD

**Issue by artemshulgin** [MedPoints/site#13]
We need to remove
![image](https://user-images.githubusercontent.com/35609528/43688324-380d5f02-98ef-11e8-9675-ec2faf0c5057.png)
and
![image](https://user-images.githubusercontent.com/35609528/43688327-41d84c0e-98ef-11e8-9186-1c7d751cbf3a.png)

**Comment by k0t0v** [comment]
Removed these items in the next commit
