### ISSUE TITLE
Fix top bar

### ISSUE THREAD

**Issue by artemshulgin** [MedPoints/site#5]
![image](https://user-images.githubusercontent.com/35609528/42941727-5c2c7a80-8b66-11e8-9493-c871e64d27d1.png)
There are a few problems with top-bar
1) Small-size font doesn't work
2) We need to hide `Medical booking in` (while we won't be given understanding how to implement it)
3) Problem with white-background for the `clinics` tab on the main screen
It should be like that
![image](https://user-images.githubusercontent.com/35609528/42941712-4f7ccb28-8b66-11e8-894d-75073938a318.png)

**Comment by k0t0v** [comment]
Implemented the font-switcher module and also refactored the layout page JS code so that only one minified JS file was included. Removed inline scripts from the layout file.
