### ISSUE TITLE
Search clinic by location impl

### ISSUE THREAD

**Issue by artemshulgin** [MedPoints/site#8]
![image](https://user-images.githubusercontent.com/35609528/43161552-0fa3e728-8f91-11e8-9616-e1c56c7c2cf5.png)
 
Api methods done, we need to implement that part
Fetching data about locations
`/api/hospitals/location`

Response:
```
{
    worldsCount : 123,
    locations : 
 [ 
    {
        name : "US",
        count : 12,
        hospitals : []
    }
 ]
}
```
All country names are code (US, UK and etc.), We need to display full names

**Comment by k0t0v** [comment]
Implemented the location filtering support on back-end and front-end
