### ISSUE TITLE
Map should work properly

### ISSUE THREAD

**Issue by artemshulgin** [MedPoints/site#9]
Currently map always shows only one address

![image](https://user-images.githubusercontent.com/35609528/43276224-aa2c8314-910c-11e8-993f-3513d6cd2525.png)

We need to get it in a proper state. 

- [x] Hospitals
- [x] Drugstores
- [x] Pharmacies

**Comment by k0t0v** [comment]
Implemented this functionality for hospitals. As soon as we have data for drugstores and pharmacies, I'll implement these categories' maps

**Comment by k0t0v** [comment]
Implemented in several commits
